### PR TITLE
bug/Issue#8

### LINKED ISSUE #8: Error in query.rs
Hello,
Thanks for this library 👍

There's an error in the query.rs file:
https://github.com/evaneaston/openweathermap/blob/f5fe87144b377f7ab21bdfeea2a4f69cb492a492/client/src/query.rs#L20
Must be:
```rust
vec![("lat", self.lat.to_string()), ("lon", self.lon.to_string())]
```

### PR DESCRIPTION
**Pull request by evaneaston**
Fixes #8
- correct bug in `Coord.query_params`
- adds some tests to `Query` impls

Other
- fixes clippy lints and fmt failures

### CODE REVIEW

File: client/src/query.rs [hunk 1]
```diff
@@ -17,7 +17,7 @@ impl Query for Coord {
     }
 
     fn query_params(&self) -> Vec<(&'static str, String)> {
-        vec![("lat", self.lat.to_string()), ("lon", self.lat.to_string())]
+        vec![("lat", self.lat.to_string()), ("lon", self.lon.to_string())]
```
Comment (evaneaston) [inline client/src/query.rs:20]: This is the actual fix for #8.
